### ISSUE TITLE
Chess board to be sized down

### ISSUE THREAD

**Issue by sellis7** [disciplesofld/chess-project#18]
Just a note to myself, but making all aware - board needs to be sized down a bit. Once I viewed it on the production side, it's too large to view without scrolling. I will tend to.

**Comment by hkawanishi** [comment]
Sounds good, thank you.  I checked the board in my phone and it looks slender and like you said it needs scrolling.

**Comment by sellis7** [comment]
Completed. Will work on mobile sizing later.
